project:
  type: website

website:
  title: "DACSS604_Final"
  navbar:
    left:
      - href: DACSS604Final.qmd
        text: Home
      - href: DACSS604SlideShow.qmd
        text: Presentation Slides
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

