project:
  type: website

website:
  title: "DACSS604_Final"
  navbar:
    left:
      - href: DACSS604_Final.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

